### ISSUE TITLE
[BUILD] Release archives checksums changed?

### ISSUE THREAD

**Issue by svenpilz** [AcademySoftwareFoundation/OpenImageIO#4003]
Hi ooio devs,

I was trying to build conan packages and noticed that checksums of the release tar.gz files are somehow different.

https://github.com/conan-io/conan-center-index/blob/master/recipes/openimageio/all/conandata.yml expects

```
url: "https://github.com/OpenImageIO/oiio/archive/refs/tags/v2.4.7.1.tar.gz"
sha256: "fd298f71e44c6776863db4b37c4a1388dba0d2eb37378afea95ab07a7cd6ecd4"
```

but the file gives

```sh
$ sha256sum OpenImageIO-2.4.7.1.tar.gz
a3dc6fdb3693eb5f1e22191e41c05800a4944f3c76daffe90bd203f956180126 *OpenImageIO-2.4.7.1.tar.gz
```

Can this be a side effect of moving the repository?

Thanks and greetings from Berlin
Sven

Refs https://github.com/conan-io/conan-center-index/issues/20365

**Comment by lgritz** [comment]
Unfortunately, we can no longer download the old file and see how it differed, but I note this:

```
$ wget https://github.com/OpenImageIO/oiio/archive/refs/tags/v2.4.7.1.tar.gz
```

gives us a file called v2.4.7.1.tar.gz, and if we look at the contents:

```
$ tar tzf v2.4.7.1.tar.gz
OpenImageIO-2.4.7.1/
OpenImageIO-2.4.7.1/.clang-format
OpenImageIO-2.4.7.1/.clang-tidy
...
```

Where did the `OpenImageIO` come from? I suppose that's taken from the repo name. And since it used to be "oiio", probably we would have seen that the old files would have looked like `oiio-2.4.7.1/...`, and therein is certainly the difference in the content of the tar file and its checksum.

I'm so sorry for the inconvenience. It never occurred to us that the checksums of OLD releases would change when we moved the repo and took the opportunity to change to the full name of the project. That was just not on our radar.

**Comment by svenpilz** [comment]
Thanks for the possible explanation. I've passed that downstream to conan center.

Guess this issue can be closed here.

**Comment by ryandesign** [comment]
We just ran into this in MacPorts.

https://trac.macports.org/ticket/69775

The way to avoid this in the future is, whenever you release a new version, to manually (well, via a script, ideally) create a source tarball and upload it as an artifact on the corresponding GitHub release.

**Comment by svenpilz** [comment]
Guess after what happened to xz a couple of weeks ago, using tarballs might no longer be considered best practice. Pinning a commit using its hash could be a way to go.

**Comment by lgritz** [comment]
Full commit hash sounds best to me, TBH.
