### ISSUE TITLE
[BUG] OIIO::ImageBuf::nsubimages returns zero for existing image

### ISSUE THREAD

**Issue by zavinator** [AcademySoftwareFoundation/OpenImageIO#4225]
**Describe the bug**

OIIO::ImageBuf::nsubimages returns zero for existing image:

```
OIIO::ImageBuf buf("existing_file.jpg"); // some file (tested JPG and TIFF)
int nsubimages = buf.nsubimages(); 
// -> 0 (incorrect) for OIIO 2.5.10.1
// -> 1 (correct) for OIIO 2.4.17.0, 2.3.15.0
```

**OpenImageIO version and dependencies**

Incorrect:

OIIO 2.5.10.1 | unknown arch?
    Build compiler: MSVS 1939 | C++14/199711
    HW features enabled at build: sse2
Dependencies:  , Boost 1.84.0, BZip2 1.0.8, FFmpeg NONE, Freetype 2.13.2, GIF 5.2.2, JPEG 62, Libheif NONE,
    libjpeg-turbo 3.0.2, LibRaw NONE, OpenColorIO NONE, OpenCV NONE, OpenEXR 3.2.3, OpenJPEG 2.5, PNG 1.6.43, Ptex
    NONE, Ptex NONE, Robinmap, TBB NONE, TIFF 4.6.0, WebP NONE, ZLIB 1.3.1

Correct:

OIIO 2.4.17.0, same dependencies

**Comment by lgritz** [comment]
We changed the meaning of this recently for 0 to mean "we can't tell without trying to read the whole file." Some file formats can know as soon as you open the file, and others need to read subimage by subimage at considerable expense in order to determine the total. We wanted to avoid this by having a "don't know, you'll just have to try" answer.

But this is flawed in two ways:

1. Although we documented this in the "oiio:subimages" attribute retrieval in the standard metadata chapter of the docs, I neglected to also explain it for ImageBuf::nsubimages(), which is basically retrieving the same data and so will have the same property.
2. Of course, some formats like JPEG that are not capable of storing multiple images ought to return 1 because it's not the case that we aren't sure how many there are.

I will address these with a patch. Sorry for the inconvenience.

**Comment by zavinator** [comment]
I've tested also the TIFF with multiple images.
So how can I get the number of images -is it in the new version possible via ImageBuf?
I've tried this, but still returning zero:

```
OIIO::ImageBuf buf("existing_file.tif"); 
buf.read(); // ?
int nsubimages = buf.nsubimages();  // -> 0
```

**Comment by lgritz** [comment]
TIFF is one of the formats where it's not going to be possible. There isn't a way to know when you open a tiff file; you have to read image by image in the file and see when you get to the end.

The question is, what do we want to have happen when you call IB::nsubimages() on such a file? Should it return 0 meaning "no inexpensive way to know, you'll have to seek one by one and see where it stops succeeding?" Or should the call itself be considered a request to do the expensive thing?

**Comment by lgritz** [comment]
Here's the history of how we got here:

We used to have every ImageBuf use ImageCache underneath, at least to get the header info, and ImageCache did the expensive thing of fully inventorying the header/spec of every image in the file up front (reading the pixel data was more lazy). But this use of the IC came at a cost, and made IBs more expensive than necessary to read an image. You want IC when your IBs are so big that you can't hold all the images in memory, but when things fit in memory (which is usually), it's just slower than if you'd read directly.

So the change we made is that now IB only uses an IC underneath when specifically requested. Otherwise, it just does a direct read instead of going through the cache. I think that matches people's expectations (for both behavior and performance) better, and they can still be IC-backed for advanced users who request it.

But here's what we lost along the way -- we no longer have that up-front read that inventoried all the subimages (including knowing exactly how many there were). For some files, like OpenEXR, we can know as soon as we open the fiel. For other files, like TIFF, you just have to read them one by one, even to find out the count.

**Comment by lgritz** [comment]
So here is my plan:

* For image formats that don't support subimages, we will report 1 (the only possible value) instead of 0 (don't know). That will fix something like a jpeg file stupidly reporting 0.
* For image formats that can know up front easily (like OpenEXR, I think), we can (and maybe already do?) report the correct number without extra expense.
* For image formats that support multiple subimages but can't tell how many without reading the whole file (like TIFF), we have three choices:
  1. Continue to report 0 "we don't know" if it's expensive to find out the total.
  2. Interpret a call to nsubimages() as a request that should be fulfilled, even if it's expensive.
  3. Make a second call -- so we have one method that returns the value if inexpensive or 0/"don't know" if it's hard, and a second method that always returns the right result even if it's expensive.

Everybody, please let me know your preferences.

**Comment by zavinator** [comment]
Perhaps I can utilize this approach instead of calling the nsubimages function. 
```
int i = 0;
while(img.read(i))
{
  // do something with img
  ++i;
}
```
By the way, this is exactly why I dislike updating libraries; there's always a chance something might break. :)

**Comment by lgritz** [comment]
Yes, that is precisely what you have to do. Well, almost! Instead of read(), you can call `init_spec()`, which will only read the header and not the pixels, and so is less expensive than read().

That's what we used to do up front, but it's not an extra expense most people usually want.

**Comment by zavinator** [comment]
I've just tested this approach, but it seems that both functions init_spec() and read() still returns true for image index greater nsubimages.

```
OIIO::ImageBuf buf(filename);
int i = 0;
while (buf.init_spec(buf.name(), i, 0))
{
	if (!buf.read(i, 0)) break;
	++i;
	assert(i < buf.nsubimages()); // OIIO 2.4 test
```

**Comment by lgritz** [comment]
Improvements proposed in #4228

**Comment by zavinator** [comment]
OIIO 3.0.0.7
For image formats that do not support multiple layers (such as PNG), the init_spec and read functions currently returns true for subimage > 0.
I believe the correct behavior should be to return false for subimage >= 1.
As a workaround, I am currently using the following code:
```
OIIO::ImageBuf buf(path);
const int nsubimages = buf.nsubimages();
int i = 0;
while (buf.init_spec(buf.name(), i, 0) && (nsubimages == 0 || i < nsubimages))
{
    // processing...
    ++i;
}
```

**Comment by lgritz** [comment]
@zavinator, I see, you are quite right! It seems that ImageBuf::init_spec does not produce an error when told to use a nonexistent subimage or MIP level. 

Additionally, I see now that while ImageInput has a supports() method that lets you query whether the file format is one that permits multi-subimages (among other things), there is no equivalent method on ImageBuf that allows you to make similar queries about the underlying file format, which would also be helpful.

**Comment by zavinator** [comment]
For TIFF images, the situation becomes problematic: if no additional layers are present, the provided workaround enters an infinite loop...

**Comment by lgritz** [comment]
> For TIFF images, the situation becomes problematic: if no additional layers are present, the provided workaround enters an infinite loop...

Are you talking about #4801? You tried with that?

**Comment by zavinator** [comment]
Thx I will check it.

I'm currently using this approach. This seems to work ok for both single/multi TIFFs.

```
for(int i = 0; buf.nsubimages() == 0 || i < buf.nsubimages(); ++i)
{
	if (!buf.read(i, 0)) break;
}
```

**Comment by zavinator** [comment]
I find one TIFF that still ends with infinite loop, also tested the changes (I've cherry picked only the changes from imagebuf.cpp and tiffinput.cpp) from #4801 - still infinite loop

[Kus 1.zip](https://github.com/user-attachments/files/20746503/Kus.1.zip)

**Comment by zavinator** [comment]
Ok, I've found a problem in my code.
Now this code works with 3.0.0.7 (without #4801)

```
for(int i = 0; buf.nsubimages() == 0 || i < buf.nsubimages(); ++i)
{
	buf.set_name(filename.toStdString()); // this fix the problem
	if (!buf.read(i, 0)) break;

       // do inplace operation on buf which destroys buf.m_name
      if (bmp.nchannels() > 1)
      {
      	  const int order[] = { 0 };
      	  OIIO::ImageBufAlgo::channels(bmp, bmp, 1, order);
      }
}
```

Maybe it is a good idea to keep the name not touched?
But for now I can live with set_name...

**Comment by lgritz** [comment]
OH, I see. Yes, operating "in place" on bmp will erase the name because it knows that the result of IBA::channels() is no longer the image in the file. Think of it more like producing an entirely new image and then replacing bmp with that image. And new images get empty names because they don't correspond to files.

To be honest, I'm not sure I trust buf.nsubimages() in the loop command, either, for the same reason: once you do the IBA::channels, you're replacing buf with a totally synthesized ImageBuf from the computation, which doesn't have subimages because it's not a file.

**Comment by zavinator** [comment]
Although the original approach works, I decided to use this instead:

```
OIIO::ImageBuf bmp(filename.toStdString());
for (int i = 0; bmp.nsubimages() == 0 || i < bmp.nsubimages(); ++i) {
    OIIO::ImageBuf buf = bmp;
    // operate on buf
}
```

By the way, it would be great if the ImageInput class - which is likely more robust - could integrate more seamlessly with ImageBuf, for instance by returning an ImageBuf instance for each subimage along with its associated metadata.

**Comment by lgritz** [comment]
> By the way, it would be great if the ImageInput class - which is likely more robust - could integrate more seamlessly with ImageBuf, for instance by returning an ImageBuf instance for each subimage along with its associated metadata.

Easy!

What form would you like this to take? A few possible (not necessarily mutually exclusive) choices:
* An ImageBuf constructor that takes an open ImageInput* where it reads from the "current" subimage of the input into the IB. (IB already has a write() method that writes to an open ImageOutput that you pass it.)
* An ImageInput::read_imagebuf() method a bit like read_image(), but returns (or reads into?) an ImageBuf rather than reading into a memory buffer.
* Some kind of iterator that, given an ImageInput* and ImageBuf*, reads each successive subimage from the ImageInput into the IB. (Choice 1: it's just the iterator and you call next() to advance; choice 2: it's a total black box and the caller doesn't iterate, but rather, what you supply is a lambda that is called for each subimage?)
* Something else I haven't thought of?

Rather than continuing the discussion on this closed issue, I will open a new issue just to discuss these possibilities.
