### ISSUE TITLE
[BUG] 2.5.17.0 testsuite references files not found in oiio-images main/RB-2.5

### ISSUE THREAD

**Issue by darix** [AcademySoftwareFoundation/OpenImageIO#4520]
would it make sense to merge 3e9caba into RB-2.5 or directly into main?

**Comment by lgritz** [comment]
3e9caba ?

**Comment by darix** [comment]
```
* 3e9caba (HEAD -> dev-3.0, origin/dev-3.1, origin/dev-3.0, origin/dev-2.6, origin/dev-2.5, main) Refactor OpenImageIO-images -- move clutter into subdirectories
* 7d821f0 (origin/main, origin/RB-3.0, origin/RB-2.5, origin/HEAD) dds: add more DDS images using DXGI formats (#7)
```

**Comment by lgritz** [comment]
RB-2.5 is the old name. Now we call it dev-2.5.

dev-2.5 in OpenImageIO-images has the refactor you're referring to. The current OpenImageIO version 2.5 (i.e., its dev-2.5 branch) refers to OpenImageIO-images/dev-2.5.

RB-2.5 is the *old name*.  We don't want the OpenImageIO-images RB-2.5 branch to include the refactor, because any old branches of OIIO itself that still refers to oiio-images/RB-2.5 expects the old directory layout.

I hope this makes sense.

Put another way:

As far as I can tell, the current OIIO dev-2.5, dev-3.0, and main (3.1) branches all refer to the OpenImageIO-images dev-2.5, dev-3.0, and dev-3.1 branches, respectively, which all have the new directory structure. We aren't going to fix any of the "RB-???" branch markers because they are no longer used, so anything referring to them can't possibly want the new directory layout.

**Comment by darix** [comment]
ok. thanks then we can close it i guess. was confusing that the branch changed :)
