### ISSUE TITLE
[BUG] --ociodisplay gives different result on v2.5.14.0 vs v3.0.0.3

### ISSUE THREAD

**Issue by michalfratczak** [AcademySoftwareFoundation/OpenImageIO#4555]
**Describe the bug**

The following command gives different results depending on oiiotool version:

`oiiotool -i Carrots.exr --ociodisplay "sRGB - Display" "ACES 1.0 - SDR Video" -o Carrots.jpeg`

I was testing with  v2.5.14.0 and v3.0.0.3 under windows. Packages were installed using vcpkg.

OCIO config file is: cg-config-v2.1.0_aces-v1.3_ocio-v2.1.ocio from https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/releases

**OpenImageIO version and dependencies**

```
rez env openimageio-2 -- oiiotool --buildinfo
OIIO 2.5.14.0 | unknown arch?
    Build compiler: MSVS 1940 | C++14/199711
    HW features enabled at build: sse2
Dependencies: Boost 1.85.0, BZip2 1.0.8, fmt 11.0.2, libjpeg-turbo 3.0.3, OpenColorIO 2.2.1, OpenEXR 3.2.3, OpenGL, PNG 1.6.43, Qt5 NONE, Qt6 NONE, Robinmap, TIFF 4.6.0, ZLIB 1.3.1
```

```
rez env openimageio-3 -- oiiotool --buildinfo
OIIO 3.0.0.3 | unknown arch?
    Build compiler: MSVS 1940 | C++17/199711
    HW features enabled at build: sse2
    No CUDA support (disabled / unavailable at build time)
Dependencies: BZip2 1.0.8, fmt 11.0.2, Freetype 2.13.3, GIF 5.2.2, Imath 3.1.12, libjpeg-turbo 3.0.4, LibRaw 0.21.3, OpenColorIO 2.2.1, OpenEXR 3.3.1, OpenGL, PNG 1.6.44, Python3 3.10.11, Qt5 NONE, Qt6 NONE, Robinmap, TIFF 4.7.0,
    ZLIB 1.3.1
```

**To Reproduce**

Carrots.exr link; https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/main/ScanLines/Carrots.exr

**Evidence**

result JPEGs:
![oiio2](https://github.com/user-attachments/assets/89632d78-e3e8-41a9-86da-885d6c87467e)
![oiio3](https://github.com/user-attachments/assets/461a2716-882b-45ca-9655-0f4e3f712bdc)

**Comment by michalfratczak** [comment]
Here it is...

oiio v2:

```
OpenColorIO 2.2.1
Color config: ocio://default
Known color spaces:
    - ACES2065-1 (linear)
      aliases: aces2065_1, "ACES - ACES2065-1", lin_ap0
    - ACEScc
      aliases: "ACES - ACEScc", acescc_ap1
    - ACEScct
      aliases: "ACES - ACEScct", acescct_ap1
    - ACEScg (linear)
      aliases: "ACES - ACEScg", lin_ap1
    - "Linear P3-D65" (linear)
      aliases: lin_p3d65, "Utility - Linear - P3-D65"
    - "Linear Rec.2020" (linear)
      aliases: lin_rec2020, "Utility - Linear - Rec.2020"
    - "Linear Rec.709 (sRGB)" (linear)
      aliases: lin_rec709_srgb, "Utility - Linear - Rec.709", lin_rec709, lin_srgb, "Utility - Linear - sRGB"
    - "Gamma 1.8 Rec.709 - Texture"
      aliases: g18_rec709_tx, "Utility - Gamma 1.8 - Rec.709 - Texture", g18_rec709
    - "Gamma 2.2 AP1 - Texture"
      aliases: g22_ap1_tx, g22_ap1
    - "Gamma 2.2 Rec.709 - Texture"
      aliases: g22_rec709_tx, "Utility - Gamma 2.2 - Rec.709 - Texture", g22_rec709
    - "Gamma 2.4 Rec.709 - Texture"
      aliases: g24_rec709_tx, g24_rec709, rec709_display, "Utility - Rec.709 - Display"
    - "sRGB Encoded AP1 - Texture"
      aliases: srgb_encoded_ap1_tx, srgb_ap1
    - "sRGB - Texture"
      aliases: srgb_tx, "Utility - sRGB - Texture", srgb_texture, "Input - Generic - sRGB - Texture"
    - Raw
      aliases: "Utility - Raw"
Known roles:
    - aces_interchange -> ACES2065-1
    - cie_xyz_d65_interchange -> CIE-XYZ-D65
    - color_picking -> "sRGB - Texture"
    - color_timing -> ACEScct
    - compositing_log -> ACEScct
    - data -> Raw
    - matte_paint -> "sRGB - Texture"
    - scene_linear -> ACEScg
    - texture_paint -> ACEScct
Known looks:
    - "ACES 1.3 Reference Gamut Compression"
Known displays: (* indicates default)
    - "sRGB - Display" (*)
      views: "ACES 1.0 - SDR Video" (*), Un-tone-mapped, Raw
    - "Rec.1886 Rec.709 - Display"
      views: "ACES 1.0 - SDR Video" (*), Un-tone-mapped, Raw
    - "Rec.2100-PQ - Display"
      views: "ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)" (*), Un-tone-mapped, Raw
    - "ST2084-P3-D65 - Display"
      views: "ACES 1.1 - HDR Video (1000 nits & P3 lim)" (*), Un-tone-mapped, Raw
    - "P3-D65 - Display"
      views: "ACES 1.0 - SDR Cinema" (*), Un-tone-mapped, Raw
```

oiio v3:
```

OpenColorIO 2.2.1
Color config: ocio://default
Known color spaces:
    - ACES2065-1 (linear)
      aliases: aces2065_1, "ACES - ACES2065-1", lin_ap0
    - ACEScc
      aliases: "ACES - ACEScc", acescc_ap1
    - ACEScct
      aliases: "ACES - ACEScct", acescct_ap1
    - ACEScg (linear)
      aliases: "ACES - ACEScg", lin_ap1
    - "Linear P3-D65" (linear)
      aliases: lin_p3d65, "Utility - Linear - P3-D65"
    - "Linear Rec.2020" (linear)
      aliases: lin_rec2020, "Utility - Linear - Rec.2020"
    - "Linear Rec.709 (sRGB)" (linear)
      aliases: lin_rec709_srgb, "Utility - Linear - Rec.709", lin_rec709, lin_srgb, "Utility - Linear - sRGB"
    - "Gamma 1.8 Rec.709 - Texture"
      aliases: g18_rec709_tx, "Utility - Gamma 1.8 - Rec.709 - Texture", g18_rec709
    - "Gamma 2.2 AP1 - Texture"
      aliases: g22_ap1_tx, g22_ap1
    - "Gamma 2.2 Rec.709 - Texture"
      aliases: g22_rec709_tx, "Utility - Gamma 2.2 - Rec.709 - Texture", g22_rec709
    - "Gamma 2.4 Rec.709 - Texture"
      aliases: g24_rec709_tx, g24_rec709, rec709_display, "Utility - Rec.709 - Display"
    - "sRGB Encoded AP1 - Texture"
      aliases: srgb_encoded_ap1_tx, srgb_ap1
    - "sRGB - Texture"
      aliases: srgb_tx, "Utility - sRGB - Texture", srgb_texture, "Input - Generic - sRGB - Texture"
    - Raw
      aliases: "Utility - Raw"
Known roles:
    - aces_interchange -> ACES2065-1
    - cie_xyz_d65_interchange -> CIE-XYZ-D65
    - color_picking -> "sRGB - Texture"
    - color_timing -> ACEScct
    - compositing_log -> ACEScct
    - data -> Raw
    - matte_paint -> "sRGB - Texture"
    - scene_linear -> ACEScg
    - texture_paint -> ACEScct
Known looks:
    - "ACES 1.3 Reference Gamut Compression"
Known displays: (* indicates default)
    - "sRGB - Display" (*)
      views: "ACES 1.0 - SDR Video" (*), Un-tone-mapped, Raw
    - "Rec.1886 Rec.709 - Display"
      views: "ACES 1.0 - SDR Video" (*), Un-tone-mapped, Raw
    - "Rec.2100-PQ - Display"
      views: "ACES 1.1 - HDR Video (1000 nits & Rec.2020 lim)" (*), Un-tone-mapped, Raw
    - "ST2084-P3-D65 - Display"
      views: "ACES 1.1 - HDR Video (1000 nits & P3 lim)" (*), Un-tone-mapped, Raw
    - "P3-D65 - Display"
      views: "ACES 1.0 - SDR Cinema" (*), Un-tone-mapped, Raw
Named transforms:
    - "Rec.1886 - Curve"
    - "sRGB - Curve"
```

**Comment by zachlewis** [comment]
This appears to reflect differences the heuristics OIIO-2.5 and OIIO-3.0 use for inferring the source color space encoding when not otherwise manually provided.

The difference between the first (OIIO-2.5) and second (OIIO-3) renderings is that the first example assumes the source color space is ACEScg, and the second example assumes the source encoding is Linear Rec.709. 

The following command produces a match for the OIIO-2.5 example:
`$ oiiotool -i Carrots.exr --iscolorspace ACEScg --ociodisplay "sRGB - Display" "ACES 1.0 - SDR Video" -o Carrots.jpeg`

This is kind of an unfortunate example, because Carrot.exe's metadata tells two different stories about the color encoding:

```bash 
$ oiiotool --info -v ../Carrots.exr
Reading ../Carrots.exr
../Carrots.exr       :  600 x  400, 4 channel, half openexr
    channel list: R, G, B, A
    adoptedNeutral: 0.32168, 0.33767
    cameraLabel: "Sony SLT-A99"
    cameraMake: "Sony"
    cameraModel: "SLT-A99"
    chromaticities: 0.7347, 0.2653, 0, 1, 0.0001, -0.077, 0.32168, 0.33767
    compression: "zip"
    effectiveFocalLength: 120
    ExposureTime: 0.625
    FNumber: 8
    isoSpeed: 100
    lensModel: "70-300mm F4.5-5.6 G SSM"
    PixelAspectRatio: 1
    screenWindowCenter: 0, 0
    screenWindowWidth: 1
    oiio:ColorSpace: "lin_rec709"
    oiio:subimages: 1
```

The `chromaticities` key indicates AP0 chromaticities, but the `oiio:ColorSpace` key is set to "lin_rec709".  And unfortunately, neither is a match for the baseline.

So, seems to be OIIO-3.0 correctly identifying the source color space in the OCIO config from the alias specified in the `oiio:ColorSpace` metadata key (which happens to be incorrect); but OIIO-2.5 can't seem to reconcile "lin_rec709" in the same default OCIO-2 config. 

I'd hazard to guess this has something to do with the fact that in this OCIO config, "lin_rec709" is only an alias for the color space named "Linear Rec.709 (sRGB)", and not the actual name of a discrete color space (like it is in the OCIO-1 ACES-1.2 and earlier configs, with all the luts); and OIIO-3 is using the OCIO API's newer methods for identifying color spaces from strings, while OIIO-2.5 is using an older method that only considers color space names. Since there is no color space named "lin_rec709" in the config, OIIO fails over to using the OCIO config author's intended default encoding (ACEScg in this case).


I'd be curious to know if this exact same command produces different results in OIIO-2.5 depending on whether or not $OCIO points to the ACES-1.2 config, or any other config that has a "lin_rec709" color space. 



In any case, I think OIIO-3.0 is doing what it should be doing -- which is, correctly inferring a source OCIO color space from OIIO-specific metadata.

**Comment by lgritz** [comment]
You are right except for one detail: the "oiio:ColorSpace" metadata is not in the file, it's added by OIIO upon read. What ii infers changed between versions, and is based on the following unfortunate combination:

1. We don't actually use the chromaticities in exr files to assign color space, because we just don't trust it and have encountered too many files where it's wrong. I think this is the general feeling of the OpenEXR TSC -- we want to retire those attributes as irredeemably unreliable and add a new one for color space name.
2. OpenEXR files are assumed to be a linear space, but which one?
3. OIIO 2.5 assumed it was the scene_linear of the active OCIO config, but this led to inconsistent behavior that varied depending on which version of OCIO was built against (if any) and what the OCIO config (if any) used for scene_linear.
4. OIIO 3.0, which by the way requires OCIO 2.2+, assumes that an unlabeled OpenEXR file is "lin_rec709", since this seems like the most likely color space of a randomly chosen image from all the unlabeled exr images in the universe.

You can argue that this choice is not good, or that changing the behavior from 2.5 to 3.0 is not good, but any way you shake it, we're talking about unlabeled files, so whatever you assume (including nothing at all) is going to be wrong in some cases. We're just trying to guess the least likely to be wrong choice.

The eventual place we'd like to get is for OpenEXR to have an officially designated metadata name for the color space, which is expected to be one of the Color Interop names, and that will be considered reliable in the future. (Still leaves us with the guessing game for files that are completely unlabeled.)

Does everybody know about the `--autocc` option to oiiotool? Among other things, it will automatically infer a color space from the filename (if it contains the name of a color space in the OCIO config). This is pretty common, for example, at my workplace, you will NEVER EVER find a file called "foo.exr", it will always be something like "foo_acescg.0001.exr".

**Comment by michalfratczak** [comment]
Thanks for fast and informative answers. So my problem was I did not use --iscolorspace flag and this solves the issue (closing).

@zachlewis 
These two commands produce the same result:
aces 1.2 config:
rez env openimageio-2 -- oiiotool -i .\Carrots.exr  --ociodisplay "ACES" "sRGB"  -o carrots_oiio2_aces_1.2.jpeg
aces 1.3 config:
![carrots_oiio2_aces_1 2](https://github.com/user-attachments/assets/eafc1fc1-5bab-43e0-9df7-f79275f29773)
![carrots_oiio2_aces_1 3](https://github.com/user-attachments/assets/2a08b0c6-5034-426b-b304-30b0bd221249)

rez env openimageio-2 -- oiiotool -i .\Carrots.exr  --ociodisplay  "sRGB - Display" "ACES 1.0 - SDR Video"   -o carrots_oiio2_aces_1.3.jpeg
