### ISSUE TITLE
Feature request: add STDIN command input to oiiotool

### ISSUE THREAD

**Issue by hhm0** [AcademySoftwareFoundation/OpenImageIO#645]
It would be great to be able to give commands to `oiiotool` via STDIN (on supporting platforms), in addition to providing commands as command line parameters. This way, `oiiotool` can be used interactively, and can take a series of commands larger than the command line length-limit.

This can either be enabled by using things like `isatty` http://pubs.opengroup.org/onlinepubs/9699919799/functions/isatty.html on POSIX, or by a command line flag. The question remains, how to combine the commands from the params and from STDIN: either only allow one of these to be used at the same time; or execute the commands from one, first (I suppose the params first, since STDIN length is often effectively unlimited.

A nice/easy way to code this, would be to lex STDIN, and then have a class or functions which simulate the command line processing functions (maybe just splitting on spaces, and on quotes if needed), but taking input from STDIN instead. This way the code requires minimal change.

**Comment by lgritz** [comment]
I don't discount the idea of allowing oiiotool to, basically, be able to read command line arguments from stdin. In fact, it's a rather neato idea. I'd be happy for somebody to pick it up. But since nobody has for 10 years (nor have people been beating down the door asking for it), I'm going to close to declutter the issue list.

Anybody reading who is sad about this and wants to implement it should feel free to re-open or just submit a PR that makes it work.
